-- CreateTable
CREATE TABLE "FicheCambiste" (
    "id" SERIAL NOT NULL,
    "dateEnregistrement" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "photoIDPath" TEXT,
    "nomPrenom" TEXT NOT NULL,
    "sexe" TEXT NOT NULL,
    "lieuNaissance" TEXT,
    "dateNaissance" TIMESTAMP(3),
    "nationalite" TEXT,
    "documentIdentite" TEXT,
    "adresse" TEXT,
    "telephone" TEXT NOT NULL,
    "email" TEXT,
    "associationNom" TEXT,
    "associationNumero" TEXT,
    "associationResponsable" TEXT,
    "associationContact" TEXT,
    "garantieNature" TEXT,
    "changeManuel" BOOLEAN NOT NULL DEFAULT false,
    "airtelMoney" BOOLEAN NOT NULL DEFAULT false,
    "mPesa" BOOLEAN NOT NULL DEFAULT false,
    "orangeMoney" BOOLEAN NOT NULL DEFAULT false,
    "afrimoney" BOOLEAN NOT NULL DEFAULT false,
    "venteTelecom" BOOLEAN NOT NULL DEFAULT false,
    "autresActivites" TEXT,
    "lieuActivite" TEXT,
    "anciennete" TEXT,
    "volume" TEXT,
    "sources" TEXT,
    "soussigne" TEXT,
    "nomAssociationAtteste" TEXT,
    "nomResponsableAssociation" TEXT,
    "lieuFait" TEXT,
    "dateEngagement" TIMESTAMP(3),
    "numEnregistrement" TEXT,
    "agentNom" TEXT,
    "dateAutorite" TIMESTAMP(3),

    CONSTRAINT "FicheCambiste_pkey" PRIMARY KEY ("id")
);
